### ISSUE TITLE
Visualitzar l'administrador als trams

### ISSUE THREAD

**Issue by antifeudalista** [HashtagsXRep/hashtagsxrep#101]
Estaria bé veure qui és l'administrador de cada tram. Restringint-ne o no la visibilitat (si és que a la llarga els trams són visibles a tots els taggers).

**Comment by alextremp** [comment]
La gestió d'administradors també hauria de ser manual, potser sí que seria millor gestionar els admins i backups a la web i deixem el excel

**Comment by alextremp** [comment]
no és viable fer-ho sobre aqueta versió, ho he d'aparcar per més endavant
