### ISSUE TITLE
Identificar usuaris registrats

### ISSUE THREAD

**Issue by antifeudalista** [HashtagsXRep/hashtagsxrep#102]
Pues eso, poder diferenciar els que s'han registrat a la web dels que no ho han fet mai.

**Comment by alextremp** [comment]
Entenc que això és a la secció privada, no??

**Comment by antifeudalista** [comment]
Suposo, la issue és de l'Onix, ella no podia posar-ho i ho he fet jo. Pregunta-li a ella a veure.

**Comment by alextremp** [comment]
Relacionat amb aquesta nova issue, 
https://github.com/HashtagsXRep/hashtagsxrep/issues/103

Lo millor seria posar:

1. Marca a usuaris que són registrats i estan a trams 
2. Marca a usuaris que només són registrats 
3. Marca a usuaris que només són a trams i no han entrat a la web
4. Usuaris que participen sovint i no són ni a la web ni a trams, potencialment formarien part de forma més activa si contactem

**Comment by alextremp** [comment]
Petit problema:
- per poder-los identificar al rànquin general, la consulta SQL d'extracció del rànquing es complicaria molt més de lo que ja està... potser la postposo per la versió 2, de moment l'he de pensar millor :)

**Comment by raquelprat** [comment]
No podem entrar tots els usuaris del tram, separats per ; com als mails i que automàticament si estan registrats posi la puntuació i si no estan registrats posi "error" o " #ref"...o el que vulguis, que no sigui un número (per no barrejar amb la puntuació). 
Quan vulguem actualitzar-los ho poguem tornar a fer, entrat tots els usuaris de cop separats per ; (per no tenir que revisar un a un quin hi és i quin no)

**Comment by alextremp** [comment]
Lo d'entrar-los tots de cop, us serviria per actualitzar la llista del tram??
o sigui, que fes algo com:
1- eliminar tots els usuaris del grup TRAM X
2- donar d'alta tots els usuaris informats
3- indicar quins no s'han pogut donar d'alta o whatever

es podria fer sí, ho poso en una issue diferent, aquesta d'aquí (la #102) no la puc fer amb la versió actual

**Comment by raquelprat** [comment]
Es poden fer tots a la vegada, separats pel caràcteer que ens diguis?
Els usuaris no informats podrien sortir a la llista però amb "error" o
alguna altre manera, però que sortissin? (ja se que els usuaris estan
repetits, és un exemple 😅)

[image: Captura de pantalla 2019-02-19 a las 11.18.28.png]

Raquel Prat
Carrer Ramón Turró, 21 - 08389 Palafolls
mail: raquelprat@icloud.com
telf.678 405 930



Missatge de Alex Castells <notifications@github.com> del dia dt., 19 de
febr. 2019 a les 10:40:

**Comment by alextremp** [comment]
Sí sí, no problem, ja miraré com fer-ho cabre xD

Aquesta tasca l'he mogut aquí ==> #113 

Parlem-ne allí millor :)

Entenc que lo ideal és poder fer un copy paste directament des del excel no?

**Comment by raquelprat** [comment]
Exacte, si tenim el tram sencer a la web, fem copy paste.
No se si es demanar molt que a part de grups Trams, que hi hagués un grup general on sortis tots els usuari i grup (Tram) a que pertanyen i els que no tenen grup pq han entrat sense estar a cap tram (que ara queden perduts)
Encara que surtin repetits els que estan a més d'un tram, això no és problema

**Comment by alextremp** [comment]
porto uns dies fent lo d'identificar els usuaris registrats, però es compliquen massa les dades a consultar pels rànquings, ho aparco per més endavant - no ho veig viable a la versió actual
