### ISSUE TITLE
Proposta enquesta

### ISSUE THREAD

**Issue by MonicaMF** [HashtagsXRep/hashtagsxrep#105]
Comento: quan entres a la web, m ha costat saber on fer l enquesta, ja que només posa votació. I si posem enquesta/votació?

**Comment by antifeudalista** [comment]
Aquest botó abans es deia enquestes, i tant en Joan com jo, vam demanar que es digués votació.
Potser, hauria de sortir ressaltat amb un text que digués ATAC D'AVUI, i sortís el primer de tots.

**Comment by MonicaMF** [comment]
Opino q es liaran igual pel qui entra, quan mes clar el missatge millor.
Posaria millor PROPOSTA ENQUESTA

**Comment by antifeudalista** [comment]
Si és així, a les 17 hores caldria canviar-ho per votació, ja que no es poden entrar propostes.

**Comment by MonicaMF** [comment]
Per aixó deia de fer en el mateix boto enquesta/votacio...

**Comment by antifeudalista** [comment]
L'Àlex segur que pot fer hi digui -no sé- PROPOSA i que a les 17 digui VOTA. O propostaenquestavotació, lu que sigui que a les 17 canviï

**Comment by alextremp** [comment]
Canviar Enquesta per Votació està clar que va ser un error....
Avui m'han preguntat més d'un cop com trobar l'enquesta. 
Nosaltres també li diem Enquesta.. 

Crec que lo més lògic seria dir-li enquesta.. 

- afegim propostes a l'enquesta
- votem propostes de l'enquesta
O sigui, una cosa són les accions que s'hi fan depenent de l'hora, però el botó crec que s'hauria de dir Enquesta 🤷‍♂️

Fem una enquesta per decidir-ho? 😂

**Comment by MonicaMF** [comment]
Em semble perfecte posar les dues accions
Fem l enquesta 🤗🤗🤗
