### ISSUE TITLE
Normativa propostes

### ISSUE THREAD

**Issue by antifeudalista** [HashtagsXRep/hashtagsxrep#111]
A la pàgina de propostes, considero interessant posar un botó que obri un menú (semblant al de "com es puntua" del rànquing) amb les normes per proposar HT:
--Què sigui nou (o com a màxim que tingui 25 tuits)
--La llargada (malgrat la redundància que la mateixa web te'l rebutgi)
--Que no sigui en contra Crida, ERC, Primàries, CUP, JxCat, etc. 

Ens estalviarem moderar uns quants HT

**Comment by alextremp** [comment]
Ja hi és!!! 😂 😂
Bé, no és un botó, és un text que és visible en tot moment sobre el formulari!
