### ISSUE TITLE
Pàgina d'inici estàtica.

### ISSUE THREAD

**Issue by antifeudalista** [HashtagsXRep/hashtagsxrep#112]
Seia interessant per a mi, que tinc un PC lent i vell, poder aturar el moviment de les imatges, ja que la meva CPU es posa al 100% de rendiment amb molta facilitat.
Ja sé que va contra la teva visió estètica de la web, però a mi em solucionaria un tema

**Comment by alextremp** [comment]
he tret el moviment de les images, mira si tal com està va bé xD
ara només es manté la rotació entre les 6 imatges de fons

**Comment by antifeudalista** [comment]
molt millor. 
Però em sap greu que la web hi surti perdent.
Vaja, em sembla que la meva sol·licitud era molt personal
