### ISSUE TITLE
Volcar tota la lectura de Twitter en 1 instrucció 

### ISSUE THREAD

**Issue by alextremp** [HashtagsXRep/hashtagsxrep#40]
Ara mateix és tarda més d'un minut en volcar 100 tweets degut a les limitacions i separació física dels servidors.

Revisar la creació d'un multi insert de 100 registres.

**Comment by antifeudalista** [comment]
Els tuits amb fotos, enquestes, o links costen més de tractar?

**Comment by alextremp** [comment]
No, es tarda el mateix (de fet la web no processa la info dels adjunts dels tweets). 
Tarda un munt pq es fa:
- 1 crida per usuari a actualitzar (tots els usuaris / autors de tweets s'inserten si són nous o se n'actualitza la info si existien)
- 1 inserció per cada tweet

Això pot acabar en màx 200 crides a la base de dades, que està a Europa mentre que el servidor de la web està a EEUU. 
Un bon lio 😂

**Comment by alextremp** [comment]
Tanco. S'inclou com a canvi a l'evolució de la web a la versió 2.
Ara mateix suposaria un canvi massa gran, així que millor esperar a refer tota la part de backend.
