### ISSUE TITLE
Segmentació x Trams (Mon)

### ISSUE THREAD

**Issue by TxikiVG** [HashtagsXRep/hashtagsxrep#44]
ITEMS WEB

1. Segmentation x trams (cada admin que ho pugui fer) I estadistiques

**Comment by alextremp** [comment]
L'he de postposar: ara mateix aquesta tasca em suposaria massa feina i serà més fàcil implementar-ho a la versió 2 de la web (previsió 1 mes)

**Comment by alextremp** [comment]
Al final l'he fet per que puguem tenir una mínima visió dels usuaris dels trams xD

- tindrem llista dels trams
- a cada tram podrem afegir/eliminar usuaris (manualment a la web, no connectat a twitter)
- podrem veure un rànquing intern de cada tram (que serà el rànquing general, filtrat pels usuaris del tram, deixant a zero punts - al final del rànquing - els usuaris del tram que no hagin participat)
