### ISSUE TITLE
Poder filtrar els hashtags

### ISSUE THREAD

**Issue by loida17** [HashtagsXRep/hashtagsxrep#55]
Que hi hagi possibilitat de filtrar els hashtags que ja estàn molt gastats

**Comment by antifeudalista** [comment]
I que el proposant del # rebi un missatge avisant-lo.
(quan es pugui, como no?)

**Comment by TxikiVG** [comment]
Llençar procediment de cerca a TW per comprovar si HT ja s'ha fet servir.

**Comment by alextremp** [comment]
fet, ara quan algú posi un hashtag que 
- s'ha fet servir almenys 10 cops durant els anteriors 7 dies
- o s'ha fet servir en algun dels nostres propis atacs

se li mostrarà un missatge d'error amb el motiu, i se l'obligarà a canviar de hashtag

**Comment by loida17** [comment]
Ets el putu amo! 🙌🏻

El dg., 20 de gen. 2019, 05:13, Alex Castells <notifications@github.com> va
escriure:
