### ISSUE TITLE
icones en la redacció del tema

### ISSUE THREAD

**Issue by antifeudalista** [HashtagsXRep/hashtagsxrep#62]

**Comment by alextremp** [comment]
Validat: veig bé la teva proposta amb icones tant a mòbil com a PC, potser et va fallar algo del navegador??? si ho segueixes veient igual, passa més info (navegador, sistema operatiu, ...) que lo dels emojis he descobert fent aquesta web que és tot un món de problemes d'encoding xD

**Comment by antifeudalista** [comment]
chrome, windows 7
