### ISSUE TITLE
llista per votació

### ISSUE THREAD

**Issue by antifeudalista** [HashtagsXRep/hashtagsxrep#63]

**Comment by antifeudalista** [comment]
Visualitzar llista i que els temes s'obrin (o despleguin) quan hi cliquis a sobre. O al PC, quan hi passis el cursor per sobre

**Comment by antifeudalista** [comment]
Abans de la votació. Només llegir els temes si t'interessen els #

**Comment by alextremp** [comment]
No sé si fer-la aquesta, crec que tal com està és millor que el que propsoses 🙅‍♂️ 
Pensa que hi ha gent que no sabrà que es pot desplegar el hashtag per veure el tema i per tant no el llegirien...

**Comment by antifeudalista** [comment]
què hi farem😏

**Comment by alextremp** [comment]
De moment la tanco. Me la deixo anotada per quan estigui llesta la versió 2 de la web.
