### ISSUE TITLE
tauler de proposants

### ISSUE THREAD

**Issue by antifeudalista** [HashtagsXRep/hashtagsxrep#64]
![panels](https://user-images.githubusercontent.com/46726638/51438733-34f7fd00-1cb0-11e9-8d7a-33b418287c53.jpg)
![panels2](https://user-images.githubusercontent.com/46726638/51438734-34f7fd00-1cb0-11e9-9ea2-461487289b4a.jpg)
antes/ después?

**Comment by alextremp** [comment]
Fet :)
