### ISSUE TITLE
Fer visibles les propostes pels admins

### ISSUE THREAD

**Issue by antifeudalista** [HashtagsXRep/hashtagsxrep#73]

**Comment by alextremp** [comment]
@antifeudalista et podries encarregar tu de fer una normativa que tingui un "format nítid / hiper-resumit / senzill-a-més-no-poder" que sigui el que enllaçarem a la web?
Quantes menys paraules tingui, millor, per si cal afegir-lo als "hashtags cancelats" = preferiblement no hauria d'ocupar més de mitja pantalla d'un mòbil, o màxim màxim la pantalla del mòbil, pq et facis una idea :)

**Comment by alextremp** [comment]
La funcionalitat de moderació ja està completa :)
