### ISSUE TITLE
A votació inserir missatge

### ISSUE THREAD

**Issue by antifeudalista** [HashtagsXRep/hashtagsxrep#75]
"En cas d'empat, qui estigui més amunt en el nostre rànquing serà la proposta guanyadora

**Comment by alextremp** [comment]
**Sortirà aquest missatge, només en cas que hi hagi empat (sinó, no es veurà cap aclaració)**

<img width="267" alt="captura de pantalla 2019-01-30 a las 1 03 15" src="https://user-images.githubusercontent.com/20399660/51948969-e0c8e780-242a-11e9-8f43-124219069880.png">
